server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: customers-service
          uri: lb://customers-service
          predicates:
            - Path=/api/customers/**
        - id: accounts-service
          uri: lb://accounts-service
          predicates:
            - Path=/api/accounts/**
        - id: transactions-service
          uri: lb://transactions-service
          predicates:
            - Path=/api/transactions/**

#Log
logging:
  level:
    root: info
    org.springframework.cloud.gateway:
      - args:
          trace
      - route:
          RouteDefinitionRouteLocator: info

#Eureka client
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}