server:
  port: 0

spring:
  application:
    name: customers-service
  datasource:
    url: jdbc:h2:file:./database/customers-service-db
    driverClassName: org.h2.Driver
    username: customers-service
    password: customers-service-password
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

springdoc:
  swagger-ui:
    show-extensions: true
    show-common-extensions: true
  use-fqn: true

#Eureka client
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}