server:
  port: 0

spring:
  application:
    name: transactions-service
  datasource:
    url: jdbc:h2:file:./database/transactions-service-db
    driverClassName: org.h2.Driver
    username: transactions-service
    password: transactions-service-password
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

#Eureka client
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}