server:
  port: 0

mongodb:
  database: products
  username: mongo-ntt
  password: mongo-ntt-password

spring:
  application:
    name: transactions-service
  data:
    mongodb:
      uri: mongodb+srv://${mongodb.username}:${mongodb.password}@nttjavabootcamp.co3ynbb.mongodb.net/NttJavaBootcamp?retryWrites=true&w=majority&appName=NttJavaBootcamp
springdoc:
  show-actuator: false

#Eureka client
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}